trigger:
  branches:
    include:
      - source

pool:
  name: Default  # Nom du pool
  demands:
    - Agent.Name -equals MYAGENT  # Spécifie l'agent exact

stages:
- stage: Build
  displayName: "Build and Test Stage"
  jobs:
  - job: BuildJob
    displayName: "Build and Run Tests"
    steps:
      - checkout: self
        displayName: "Checkout Repository"

      - script: |
          echo "Installing Maven if not present..."
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version
        displayName: "Install Maven"

      - script: |
          echo "Compiling the project using Maven"
          mvn compile
        displayName: "Maven Compile"
