trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    strategy:
      maxParallel: 1  # Limite à 1 job parallèle
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        echo "Restoring NuGet packages"
        dotnet restore
      displayName: 'Restore NuGet Packages'

    - script: |
        echo "Building the project"
        dotnet build --configuration $(buildConfiguration)
      displayName: 'Build Project'

    - script: |
        echo "Running unit tests"
        dotnet test --configuration $(buildConfiguration)
      displayName: 'Run Unit Tests'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Deploying the application"
      displayName: 'Deploy Step'