trigger:
  branches:
    include:
      - main
      - source
pool: default

stages:
- stage: Build
  displayName: "Build and Test Stage"
  jobs:
  - job: BuildJob
    displayName: "Build and Run Tests"
    steps:
      - checkout: self
        displayName: "Checkout Repository"

      - task: Maven@3
        displayName: "Run Maven Clean"
        inputs:
          mavenVersionOption: 'Default'
          mavenPomFile: 'pom.xml'
          goals: 'clean'
          publishJUnitResults: false

      - script: |
          echo "Compiling the project using Maven"
          mvn compile
        displayName: "Maven Compile"

