trigger:
  branches:
    include:
      - main
      - source

pool:
  name: Default
  demands:
    - maven

stages:
- stage: Build
  displayName: "Build and Test Stage"
  jobs:
  - job: BuildJob
    displayName: "Build and Run Tests"
    steps:
      - checkout: self
        displayName: "Checkout Repository"

      - script: |
          echo "Installing Maven if not present..."
          sudo apt-get update
          sudo apt-get install -y maven
          mvn -version
        displayName: "Install Maven"

      - script: |
          echo "Running Maven Clean"
          mvn clean
        displayName: "Maven Clean"

      - script: |
          echo "Compiling the project using Maven"
          mvn compile
        displayName: "Maven Compile"
