# application-docker.yml
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/SahtyApp?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
services:
web:
  image: dockerimage
  ports:
    - "8089:80"
