package com.example.sahtyapp1.Entity;

public enum Ville {
    Béja,
    Medjez_el_Bab,
            Goubellat,
    Testour,
            Nefza,
    Bizerte,
    Menzel_Bourguiba,
    Mateur,
    Ras_Jebel,
    Tinja,
    Nabeul,
    Hammamet,
            Korba,
    Menzel_Temime,
    Kelibia,
    Manouba,
    Oued_Ellil ,
    Tebourba,
    Douar_Hicher,
    El_Batan,
    Ben_Arous,
    Hammam_Lif,
    Rades,
            Ezzahra,
    Mornag,
    Ariana,
    Soukra,
    Raoued,
            Mnihla,
    Kalaat_El_Andalous,
    Tunis,
    Marsa,
    Carthage,
    Bardo,
    Kram
}
